#!/bin/bash
#
# Copyright (c) 2019 Stefaan Coussement
# MIT License
#
# more info: https://github.com/stefaanc/ptsession
#

echo -e ""
echo -e "      Colorized"
echo -e "      -------------------------- "
echo -e "     \e[90;40m Dim Screen Text            \e[0m"
echo -e "     \e[37;40m Screen Text                \e[0m"
echo -e "     \e[97;40m Bright Screen Text         \e[0m"
echo -e ""
echo -e "     \e[30;107m Bright Popup Text          \e[0m"
echo -e "     \e[90;107m Popup Text                 \e[0m"
echo -e "     \e[37;107m Dim Popup Text             \e[0m"
echo -e ""
echo -e "     \e[31;40m Red                        \e[0m"
echo -e "     \e[94;40m Orange                     \e[0m"
echo -e "     \e[33;40m Yellow                     \e[0m"
echo -e "     \e[32;40m Green                      \e[0m"
echo -e "     \e[36;40m Cyan                       \e[0m"
echo -e "     \e[34;40m Blue                       \e[0m"
echo -e "     \e[95;40m Violet                     \e[0m"
echo -e "     \e[35;40m Magenta                    \e[0m"
echo -e ""
echo -e "     \e[91;40m Traffic Red                \e[0m"
echo -e "     \e[93;40m Traffic Amber              \e[0m"
echo -e "     \e[92;40m Traffic Green              \e[0m"
echo -e "     \e[96;40m Traffic Blue               \e[0m"
echo -e ""
echo -e "      Colour Table"
echo -e "      -------------------------- "
echo -e " [0] \e[37;40m Default Foreground         \e[0m"
echo -e " [1] \e[90;107m Default Bold Foreground    \e[0m"
echo -e " [2] \e[37;40m Default Background         \e[0m"
echo -e " [3] \e[90;107m Default Bold Background    \e[0m"
echo -e " [4] \e[37;40m Cursor Tex\e[30;107mt\e[37;40m                \e[0m"
echo -e " [5] \e[37;40m Cursor Colour\e[30;107m \e[37;40m             \e[0m"
echo -e " [6] \e[30;40m ANSI Black                 \e[0m"
echo -e " [7] \e[90;40m ANSI Black Bold            \e[0m"
echo -e " [8] \e[31;40m ANSI Red                   \e[0m"
echo -e " [9] \e[91;40m ANSI Red Bold              \e[0m"
echo -e " [10]\e[32;40m ANSI Green                 \e[0m"
echo -e " [11]\e[92;40m ANSI Green Bold            \e[0m"
echo -e " [12]\e[33;40m ANSI Yellow                \e[0m"
echo -e " [13]\e[93;40m ANSI Yellow Bold (Amber)   \e[0m"
echo -e " [14]\e[34;40m ANSI Blue                  \e[0m"
echo -e " [15]\e[94;40m ANSI Blue Bold (Orange)    \e[0m"
echo -e " [16]\e[35;40m ANSI Magenta               \e[0m"
echo -e " [17]\e[95;40m ANSI Magenta Bold (Violet) \e[0m"
echo -e " [18]\e[36;40m ANSI Cyan                  \e[0m"
echo -e " [19]\e[96;40m ANSI Cyan Bold             \e[0m"
echo -e " [20]\e[37;40m ANSI White                 \e[0m"
echo -e " [21]\e[97;40m ANSI White Bold            \e[0m"
echo -e ""
